### ISSUE TITLE
rename toggle_string_cache to enable_string_cache

### ISSUE THREAD

**Issue by christophechu** [icbi-lab/infercnvpy#107]
### Report

when I changed the` toggle_string_cache` to `enable_string_cache` in read_gtf.py , another error occurred `scan_csv() got an unexpected keyword argument 'sep'`

**Comment by grst** [comment]
This sounds again like an incompatibility of the gtfparse library with polars. See https://github.com/icbi-lab/infercnvpy/issues/86

**Comment by christophechu** [comment]
thx, in order not to affect the normal use of other packages, I chose to create a new infercnv-specific environment and specify the version of 0.15.* Polars  installed after normal use of the

**Comment by grst** [comment]
I pinned gtfparse<2 in the latest release which doesn't use polars. This should fix the issue.
