### ISSUE TITLE
infercnvpy.pl.chromosome_heatmap doesn't pass dendrogram data to scanpy.pl.heatmap

### ISSUE THREAD

**Issue by jpintar** [icbi-lab/infercnvpy#109]
### Report

When `infercnvpy.pl.chromosome_heatmap` and `infercnvpy.pl.chromosome_heatmap_summary` are called with `dendrogram=True` after a dendrogram has been computed with `scanpy.tl.dendrogram`, Scanpy issues a `dendrogram data not found` warning, and re-runs `scanpy.tl.dendrogram` with default settings (which, in turn, results in `scanpy.tl.pca` being run). 

This is because Scanpy is, by default, looking for `adata.uns[f"dendrogram_{groupby}"]`, but this has not been copied to `tmp_adata` which `infercnvpy.pl.chromosome_heatmap` and `infercnvpy.pl.chromosome_heatmap_summary` pass to `scanpy.pl.heatmap`.  

The problem can be fixed by simply copying `adata.uns[f"dendrogram_{groupby}"]`, if it exists, to `tmp_adata.uns`, as is already the case with `adata.uns[f"{groupby}_colors"]`. I'd be happy to make a pull request if that's helpful.

### Version information

anndata             0.9.2
scanpy              1.9.4
infercnvpy          0.4.2

**Comment by grst** [comment]
Hi @jpintar,

a PR would be most welcome!

**Comment by grst** [comment]
Closed via #110
