### ISSUE TITLE
Adding copykat cell.line parameter?

### ISSUE THREAD

**Issue by josephreplogle** [icbi-lab/infercnvpy#123]
### Description of feature

copykat has added a mode for cell line data that has only aneuploid or diploid cells. This mode is called by setting the parameter cell.line="yes" while the default for tissue samples is cell.line="no". Is it possible to add this parameter as an option in infercnvpy.tl.copykat? Thanks!

From copykat:
#' @param  cell.line if the data are from pure cell line,put "yes"; if cell line data are a mixture of tumor and normal cells, still put "no".

**Comment by grst** [comment]
happy to accept a PR

**Comment by josephreplogle** [comment]
thanks, PR in
