### ISSUE TITLE
Per gene copy number signal.

### ISSUE THREAD

**Issue by sohrabsa** [icbi-lab/infercnvpy#128]
### Description of feature

I've noticed that on occasions, after running `cnv.tl.infercnv` the shape of `adata.obsm['X_cnv'].shape` is not equal to the size of `adata.X.shape`. 
It is possible to please get gene specific copy number values? or otherwise, a mapping for genes to the segments that comprise the columns of X_cnv?

**Comment by grst** [comment]
Hi, this is currently not possible. Since infercnvpy aggregates gene expression of several genes in a sliding window the information about individual genes is lost. 

In principle, it would be possible to store a mapping in which "bins" a certain gene is located - There's a PR open for that #58, but it has gone stale.

**Comment by sohrabsa** [comment]
Okay, got it thanks. Could you confirm that the columns of `X_cnv` are `bins` of size `window_size` please?

**Comment by grst** [comment]
That's correct, but note that the bins overlap, i.e. each gene occurs in multiple bins. 
It's described here in more detail: https://infercnvpy.readthedocs.io/en/latest/infercnv.html

**Comment by knadia07** [comment]
Hi is there a way to pull out _group of genes_  within selected chrm coordinates that have high cnv values? We want to know what are the most probable gene sets that are likely altered

**Comment by grantn5** [comment]
Hi I am working on PR and adding to #58 that will allow you to extract the per gene copy number by averaging across all the bins a given gene appears in, I will hopefully have something ready in the next 2 weeks! 

Additionally, in my refactoring I have noticed that the current implementation uses the default `np.convolve` method `full`, this means that the pyramid array is fully moved over the gene array, which does not match with the documentation for the function I have therefore updated method to `valid` which does match what the documentation suggests and to me seems more relevant to the problem as there will always be 100 genes used in each window.
