### ISSUE TITLE
Pre-processing data?

### ISSUE THREAD

**Issue by mibo1996** [icbi-lab/infercnvpy#13]
Hi,

I was wondering how pre-processing affects the data input for InferCNVpy.

I know that the data must be filtered for low-quality cells, normalized, and log-transformed before running InferCNVpy, but I was wondering if it matters if **also** computing highly variable genes, regressing out unwanted variables (e.g. total counts and percentage of mitochondrial genes), scaling, running PCA, computing neighbors, UMAP, clustering, and differential expression analysis on the data **before** running InferCNVpy affects the results?

I am mainly wondering if it matters where in the workflow InferCNV comes in, and if it does, where it should be? E.g. always before/after {these steps}, or if it doesn't matter. 

Thank you

**Comment by grst** [comment]
Hi @mibo1996,

that's a good questions and I can only answer it partly

> highly variable genes

Infercny ignores highly variable gene annotation. Subsetting to highly variable genes would lead to significantly worse results as you loose a lot of information about genomic positions. 

> running PCA, computing neighbors, UMAP, clustering, and differential expression analysis

this should have no effect either as infercnvpy only uses information in `adata.X` which is left untouched by these functions. 

> regressing out unwanted variables (e.g. total counts and percentage of mitochondrial genes), scaling

This will have an effect, but I don't know to what extent. I would suspect that it mostly changes the scale of results but that it qualitatively is still highly similar. Let me know how it goes if you try it out! 

This description of the computation steps should also help you understand what data is used and how: 
https://icbi-lab.github.io/infercnvpy/infercnv.html#computation-steps

Cheers, 
Gregor

**Comment by grst** [comment]
Feel free to reopen if there are follow-up questions.

**Comment by dKlee99** [comment]
Hello!

Thanks for creating this amazing wrapper!
I was wondering—in the tutorial, it is mentioned that infercnv requires a log-normalized count matrix, but infercnv itself states that it requires a raw count matrix as input. I'm a bit confused about which one to use.

Thanks a lot!

![Image](https://github.com/user-attachments/assets/41c87285-79d4-4774-8bcb-d9fdf1cb6ba6)

![Image](https://github.com/user-attachments/assets/d1bba750-d51c-49ea-9d85-2febfee19d8a)
