### ISSUE TITLE
Can the infercnvpy output observation.txt file like inferCNV(R)?

### ISSUE THREAD

**Issue by XinheG** [icbi-lab/infercnvpy#141]
### Description of feature

Hello,

I am attempting to reconstruct a function from R to Python that can differentiate between malignant and benign tumor cells recently, and it seems that the infercnvpy does not generate this output file as the R package. 

In R, the function that I'm trying to reconstruct utilies a direct output file named **infercnv.observations.txt**, which is the tumor cell matrix data values. This file is automatically generated by running infercnv_obj <- infercnv::run(infercnv_obj, ...). In the R version of inferCNV, this generation of the file is determined by the parameter **write_expr_matrix=T**, which appears in the function **plot_cnv** that is written in the R script [inferCNV_heatmap.R](https://github.com/broadinstitute/infercnv/blob/master/R/inferCNV_heatmap.R).

It could be seen from the code that this file is generated from the **infercnv_obj@expr.data** , then passed to obs_data in the function plot_cnv:

obs_data <- infercnv_obj@expr.data

and is finally processed by the function **heatmap.cnv** that begins from line 1,373, before written into the txt file as follow:

```
if ("matrix" %in% is(obs_data)) {
    if (write_expr_matrix) {
        flog.info(paste("plot_cnv_observations:Writing observation data to", observation_file_base, sep=" "))
        row.names(obs_data) <- orig_row_names
        write.table(as.matrix(t(obs_data[data_observations$rowInd, data_observations$colInd])), file=observation_file_base)
    }
}
```
As I am new to the python version of inferCNV, I am wondering does the infercnvpy contains the same data as the observations.txt after the analysis process is compelete?  If it does exist, how could I extract it?

Thanks a lot for answering this question, it would really help me a lot with my study.

Sincerely yours.

**Comment by grst** [comment]
Hi @XinheG, 

not sure if I correctly understood the question, but the expression values are usually available from 

```python
adata.X
```

or if you store raw value separately in 

```python
adata.raw.X
```

**Comment by XinheG** [comment]
> Hi @XinheG,
> 
> not sure if I correctly understood the question, but the expression values are usually available from
> 
> ```python
> adata.X
> ```
> 
> or if you store raw value separately in
> 
> ```python
> adata.raw.X
> ```

Thank you so much for answering. I'll go check. That would really help me a lot.
