### ISSUE TITLE
gene location and CNV calculation windows

### ISSUE THREAD

**Issue by bioorange** [icbi-lab/infercnvpy#142]
### Description of feature

the output of cnv object .obsm['X_cnv'] dose not include the information of genes, how can i locate the window of a specific gene?

**Comment by grst** [comment]
Since the latest release, you can set
```
tl.infercnvy(..., calculate_gene_values=True)
```

See the docs for more details: 
https://infercnvpy.readthedocs.io/en/latest/generated/infercnvpy.tl.infercnv.html

hope that helps, 
Gregor

**Comment by bioorange** [comment]
thanks! that helps a lot 😊👍
