### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by PietroAnc** [icbi-lab/infercnvpy#146]
### Report

Hi, I'm trying to run infercnvpy but got this error: 

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/process.py", line 210, in _process_chunk
    return [fn(*args) for args in chunk]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/process.py", line 210, in <listcomp>
    return [fn(*args) for args in chunk]
            ^^^^^^^^^
  File "/home/utente/Desktop/ongoing/EMBL-scRNA/scRNA-seq_python_course_2024/.venv/lib/python3.11/site-packages/infercnvpy/tl/_infercnv.py", line 429, in _infercnv_chunk
    chr_pos, x_smoothed, conv_df = _running_mean_by_chromosome(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/utente/Desktop/ongoing/EMBL-scRNA/scRNA-seq_python_course_2024/.venv/lib/python3.11/site-packages/infercnvpy/tl/_infercnv.py", line 333, in _running_mean_by_chromosome
    running_means, convolved_dfs = zip(*running_means, strict=False)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
"""

The above exception was the direct cause of the following exception:
...
    [402](https://file+.vscode-resource.vscode-cdn.net/usr/lib/python3.11/concurrent/futures/_base.py:402)     finally:
    [403](https://file+.vscode-resource.vscode-cdn.net/usr/lib/python3.11/concurrent/futures/_base.py:403)         # Break a reference cycle with the exception in self._exception
    [404](https://file+.vscode-resource.vscode-cdn.net/usr/lib/python3.11/concurrent/futures/_base.py:404)         self = None

ValueError: not enough values to unpack (expected 2, got 0)

I can't figure out what the problem is, there must be something going on with the chromosome column but it seems to be correct, giving the format i found in the example notebook.
Thanks in advance

### Version information

-----
anndata             0.10.8
cellbender          0.3.0
decoupler           1.8.0
harmonypy           0.0.10
infercnvpy          0.5.0
loompy              3.0.7
matplotlib          3.9.2
numba               0.60.0
numpy               1.23.5
pandas              2.2.3
pybiomart           0.2.0
pyscenic            0.12.1
scanpy              1.10.3
scipy               1.14.1
seaborn             0.13.2
session_info        1.0.0
-----
Cython                      3.0.11
PIL                         10.4.0
anyio                       NA
arrow                       1.3.0
asttokens                   NA
astunparse                  1.6.3
attr                        24.2.0
attrs                       24.2.0
babel                       2.16.0
bson                        NA
cattr                       NA
cattrs                      NA
certifi                     2024.08.30
cffi                        1.17.1
charset_normalizer          3.3.2
cloudpickle                 3.1.0
comm                        0.2.2
cupy                        13.3.0
cupy_backends               NA
cupyx                       NA
cycler                      0.12.1
cython                      3.0.11
cython_runtime              NA
cytoolz                     1.0.0
dask                        2024.2.1
dateutil                    2.9.0.post0
debugpy                     1.8.6
decorator                   5.1.1
defusedxml                  0.7.1
dill                        0.3.9
entrypoints                 0.4
executing                   2.1.0
fastjsonschema              NA
fastrlock                   0.8.2
fqdn                        NA
future                      1.0.0
gridfs                      NA
gtfparse                    2.5.0
h5py                        3.12.1
idna                        3.10
igraph                      0.11.6
importlib_metadata          NA
iniconfig                   NA
ipykernel                   6.29.5
ipython_genutils            0.2.0
ipywidgets                  8.1.5
isoduration                 NA
jedi                        0.19.1
jinja2                      3.1.4
joblib                      1.4.2
json5                       0.9.25
jsonpointer                 3.0.0
jsonschema                  4.23.0
jsonschema_specifications   NA
jupyter_events              0.10.0
jupyter_server              2.14.2
jupyterlab_server           2.27.3
kiwisolver                  1.4.7
legacy_api_wrap             NA
leidenalg                   0.10.2
llvmlite                    0.43.0
lz4                         4.3.3
markupsafe                  2.1.5
mpl_toolkits                NA
msgpack                     1.1.0
natsort                     8.4.0
nbformat                    5.10.4
numexpr                     2.10.1
numpy_groupies              0.11.2
overrides                   NA
packaging                   24.1
parso                       0.8.4
patsy                       0.5.6
platformdirs                4.3.6
pluggy                      1.5.0
polars                      0.20.31
prometheus_client           NA
prompt_toolkit              3.0.48
psutil                      6.0.0
pure_eval                   0.2.3
py                          NA
pyarrow                     14.0.2
pycparser                   2.22
pydev_ipython               NA
pydevconsole                NA
pydevd                      3.1.0
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pydot                       3.0.2
pygments                    2.18.0
pymongo                     4.10.1
pynvml                      11.4.1
pyparsing                   3.1.4
pyreadr                     0.5.2
pytest                      8.3.3
pythonjsonlogger            NA
pytz                        2024.2
rapids_dask_dependency      NA
referencing                 NA
requests                    2.32.3
requests_cache              1.2.1
rfc3339_validator           0.1.4
rfc3986_validator           0.1.1
rpds                        NA
send2trash                  NA
sitecustomize               NA
six                         1.16.0
sklearn                     1.1.3
sniffio                     1.3.1
socks                       1.7.1
sparse                      0.15.4
stack_data                  0.6.3
statsmodels                 0.14.3
tables                      3.10.1
tblib                       3.0.0
texttable                   1.7.0
threadpoolctl               3.5.0
tlz                         1.0.0
toolz                       1.0.0
torch                       2.5.1+cu124
torchgen                    NA
tornado                     6.4.1
tqdm                        4.66.5
traitlets                   5.14.3
typing_extensions           NA
uri_template                NA
url_normalize               1.4.3
urllib3                     2.2.3
vscode                      NA
wcwidth                     0.2.13
webcolors                   24.8.0
websocket                   1.8.0
xarray                      2024.3.0
yaml                        6.0.2
zipp                        NA
zmq                         26.2.0
zoneinfo                    NA
-----
IPython             8.28.0
jupyter_client      7.4.9
jupyter_core        5.7.2
jupyterlab          4.2.5
notebook            6.5.7
-----
Python 3.11.10 (main, Sep  7 2024, 18:35:41) [GCC 13.2.0]
Linux-6.8.0-49-generic-x86_64-with-glibc2.39
-----
Session information updated at 2024-11-25 14:09

**Comment by PietroAnc** [comment]
Solved, there was something wront in my adata.

**Comment by jezkoski** [comment]
@PietroAnc  What was wrong in the data? I encountered the same error but can't figure out what's wrong with my adata.

**Comment by erlun1** [comment]
Hi there,
I encountered this issue today as well. After troubleshooting, I noticed that infercnvpy only recognizes chromosome names starting with "chr" (lowercase). Names beginning with "Chr" (uppercase) or standalone numbers (e.g., "1" instead of "chr1") are not supported, which might be causing compatibility issues.

**Comment by PietroAnc** [comment]
Hi @erlun1, the error it's indeed related to a formatting problem of the chrom column, I had a similar issue and solved it formatting the column correctly.
