### ISSUE TITLE
Add copykat to tutorial

### ISSUE THREAD

**Issue by grst** [icbi-lab/infercnvpy#23]
Show that `tl.copykat` can work as drop-in replacement for `tl.infercnv`

**Comment by zhangpebbels** [comment]
could add parameter -norm.cell.names?

**Comment by jingxinfu** [comment]
would it be possible to add the `cnv_result$prediction` to the `adata.obs['copyKat']`?

**Comment by grst** [comment]
In principle, yes. 

I currently don't have time to look into it, but feel free to submit a PR with your suggestions. 

On top of that, we were experiencing a few issues with copykat, in particular copykat applies its own cell filtering strategy, s.t. the output matrix does not necessarily fit into the original `adata` object. 

Additionally we started investigating [SCEVAN](https://github.com/AntonioDeFalco/SCEVAN) which according to their preprint has superior performance over copykat.

**Comment by jingxinfu** [comment]
good to know, i submitted a [PR](https://github.com/icbi-lab/infercnvpy/pull/25) but seems to fail on generating the docs.

**Comment by grst** [comment]
Superseded by #28
