### ISSUE TITLE
CopyKAT -  got an unexpected keyword argument 'norm_cell_names'

### ISSUE THREAD

**Issue by sandrav-CGEN** [icbi-lab/infercnvpy#39]
Hi,

thanks for the nice work!
I am trying to use the copyKAT function with the parameter  'norm_cell_names'.
I receive the error message: "got an unexpected keyword argument 'norm_cell_names'" (see screenshot).
Anyone might have experienced the same problem?
![image](https://user-images.githubusercontent.com/104442627/166249779-7caf3b8b-effd-480d-b4c6-1f301204d0b8.png)

**Comment by grst** [comment]
Are you sure you have the latest version of infercnvpy? The `norm_cell_name` was added only in the latest v0.3 release a few days ago. 

Also, it should probably be a list of cells, rather than a single identifier.

**Comment by sandrav-CGEN** [comment]
Thank you! Missed that :) Great this feature was added.
Solved the problem.
