### ISSUE TITLE
Add wrapper for copyKAT

### ISSUE THREAD

**Issue by grst** [icbi-lab/infercnvpy#4]
[copyKAT](https://github.com/navinlabcode/copykat) has recently been released and appears to be superior over the infercnv method. While it might not be worth the effort reimplementing their algorithm in python, it would be nice to 
have a wrapper function around their R code from the infercnvpy interface. 

This would also enable downstream analysis using the infercnvpy visualization tools and creating the CNV-based umap based on copyKAT. 

It would probably go into a separate tool: `cnv.tl.copykat`.

**Comment by grst** [comment]
@chris-rands, @JBreunig, @rgranit, a copyKAT wrapper is now available as `infercnvpy.tl.copykat` and released in `v0.2.0`. 

A working R installation with the [copykat package](https://github.com/navinlabcode/copykat#step-1-installation) installed is required for it to work. 

Let me know if you have any feedback!

**Comment by rgranit** [comment]
Thanks @grst I'll check it out (literally)
