### ISSUE TITLE
copykat py2rpy error

### ISSUE THREAD

**Issue by diyang1354** [icbi-lab/infercnvpy#40]
Hi,
When I run copykat method with the latest version 0.3.0, the following error occured:
NotImplementedError: Conversion 'py2rpy' not defined for objects of type '<class 'pandas.core.indexes.base.Index'>'
What should I do?
Best
![image](https://user-images.githubusercontent.com/51859749/169315046-5ccf461d-487a-4a3c-a0f4-93b7c1c2fd2e.png)

**Comment by grst** [comment]
HI @diyang1354, 

can you try
```
...
norm_cell_names = norm_cell.obs.index.tolist()
...
```

**Comment by zseferbekova** [comment]
Hi @diyang1354,

What helped me was to run this after importing and before running a tool:
```
from rpy2.robjects import pandas2ri

pandas2ri.activate()
```
