### ISSUE TITLE
Ith score

### ISSUE THREAD

**Issue by rahhhm** [icbi-lab/infercnvpy#41]
In the case of ITH cna, IQR is distribution of the coefeffiient values of Pearson correlation between malignant cells for each sample taken from the gene expression matrix derived from the cnv heatmap
In the case of ITHgex, can I say that iqr is obtained from the scaling gene expression matrix?

I did the same with the matrix from infercnv(R), and I expected that the two values would be different, but the correlation was completely different, so I asked because I thought there might be some misunderstanding.

**Comment by rahhhm** [comment]
gex score was roughly comparable, but cna score was completely different.

I used infercnv.reference.txt and infercnv.observation.txt created by infercnv :: run

did I use right files?

**Comment by grst** [comment]
> or If the CNV plots are incomparable, is the difference natural?

yes, then I'd also expect the ITH score to be different. But in that case it would be interesting to know why the plots are not comparable in the first place. 

infercnvpy is not an exact re-implementation of the infercnv algorithm, but in my examples the final results were quite similar.

**Comment by rahhhm** [comment]
thank you for comment

I solved it,  I used "infercnv_obj@expr.data"

It has same order of ITH cna score with "infercnvpy.tl.ithcna"
