### ISSUE TITLE
NA/NaN/Inf in foreign function call (arg 10)

### ISSUE THREAD

**Issue by lacey359** [icbi-lab/infercnvpy#49]
when I use the copycat,it made a issue:
rpy2.rinterface_lib.embedded.RRuntimeError: Error in hclust(d, method = "ward.D2") :
  NA/NaN/Inf in foreign function call (arg 10)
 
how can I solve it?

**Comment by grst** [comment]
Any chance there are NA values in your gene expression matrix. 

If that's not the issue that sounds more like a problem with copykat itself -- infercnvpy just provides a thin wrapper that executes the R code from python. You may be better off asking for help in their repository.
