### ISSUE TITLE
genomic_position_from_gtf

### ISSUE THREAD

**Issue by Hafsa-Faeth** [icbi-lab/infercnvpy#65]
### Report

I was using genomic_position_from_gtf on my ann dataframe before running infercnv. It has always worked well for me previously but now I keep getting this error:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/111351330/210245712-3eed350d-4ac6-495e-a400-9ab1c92212e0.png">

Any suggestions? Thanks a lot!

### Version information

-----
anndata             0.8.0
celltypist          1.3.0
infercnvpy          0.4.0
matplotlib          3.5.1
numpy               1.21.6
pandas              1.5.2
pkg_resources       NA
scanpy              1.9.1
scvi                0.19.0
session_info        1.0.0
-----
PIL                 9.1.0
absl                NA
asttokens           NA
attr                21.4.0
backcall            0.2.0
beta_ufunc          NA
binom_ufunc         NA
botocore            1.24.21
brotli              NA
certifi             2021.10.08
cffi                1.15.0
charset_normalizer  2.0.12
chex                0.1.5
cloudpickle         2.0.0
contextlib2         NA
cycler              0.10.0
cython_runtime      NA
cytoolz             0.11.2
dask                2022.04.1
dateutil            2.8.2
debugpy             1.6.0
decorator           5.1.1
defusedxml          0.7.1
deprecate           0.3.2
docrep              0.3.2
entrypoints         0.4
etils               0.9.0
executing           0.8.3
flax                0.6.3
fsspec              2022.3.0
google              NA
graphviz            0.20
gtfparse            NA
h5py                3.7.0
hypergeom_ufunc     NA
idna                3.3
igraph              0.10.3
ipykernel           6.13.0
ipython_genutils    0.2.0
ipywidgets          7.7.0
jax                 0.4.1
jaxlib              0.4.1
jedi                0.18.1
jinja2              3.1.2
joblib              1.1.0
kiwisolver          1.4.2
leidenalg           0.9.1
llvmlite            0.38.0
lz4                 4.0.0
markupsafe          2.1.1
matplotlib_inline   NA
ml_collections      NA
mpl_toolkits        NA
msgpack             1.0.3
mudata              0.2.1
multipledispatch    0.6.0
natsort             8.1.0
nbinom_ufunc        NA
numba               0.55.1
numpyro             0.10.1
nvidia              NA
opt_einsum          v3.3.0
optax               0.1.4
packaging           21.3
parso               0.8.3
pexpect             4.8.0
pickleshare         0.7.5
polars              0.15.10
prompt_toolkit      3.0.29
psutil              5.9.0
ptyprocess          0.7.0
pure_eval           0.2.2
pyarrow             6.0.1
pycparser           2.21
pydev_ipython       NA
pydevconsole        NA
pydevd              2.8.0
pydevd_file_utils   NA
pydevd_plugins      NA
pydevd_tracing      NA
pygments            2.12.0
pynndescent         0.5.8
pyparsing           3.0.9
pyreadr             0.4.7
pyro                1.8.3
pytorch_lightning   1.7.7
pytz                2022.1
requests            2.27.1
rich                NA
ruamel              NA
scipy               1.8.0
six                 1.16.0
sklearn             1.0.2
snowflake           NA
socks               1.7.1
stack_data          0.2.0
statsmodels         0.13.5
tblib               1.7.0
tensorboard         2.11.0
texttable           1.6.7
threadpoolctl       3.1.0
tlz                 0.11.2
toolz               0.11.2
torch               1.13.1+cu117
torchmetrics        0.11.0
tornado             6.1
tqdm                4.64.1
traitlets           5.2.1.post0
tree                0.1.8
typing_extensions   NA
umap                0.5.3
unicodedata2        NA
urllib3             1.26.9
wcwidth             0.2.5
wrapt               1.14.1
yaml                6.0
zmq                 22.3.0
zoneinfo            NA
-----
IPython             8.3.0
jupyter_client      7.3.1
jupyter_core        4.10.0
notebook            6.4.11
-----
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) [GCC 10.3.0]
Linux-5.4.190-107.353.amzn2.x86_64-x86_64-with-glibc2.31
-----
Session information updated at 2023-01-02 14:37

**Comment by grst** [comment]
Hi @Hafsa-Faeth, 

thanks for reporting this! 

Apparently `gtfparse` returns a polars dataframe instead of a pandas dataframe in the latest version. 

This is easy to fix by adding 
```python
read_gtf(..., result_type='pandas')
```

For now, you can try to downgrade gtfparse: 
```bash
pip install "gtfparse<2"
```
