### ISSUE TITLE
inferCNV output matrix has the same dimension with different window size

### ISSUE THREAD

**Issue by YubinXie** [icbi-lab/infercnvpy#74]
### Report

Hi, thanks for the python version of inferCNV. I am trying to use the output from inferCNV to see where are the chromosome location of each CNV. I could not find the info about the output matrix in the document. 
In my case, I got a Cell number by 2118 matrix. How do I interpret the 2118 here? And I was assuming it is the average mean for genes in that window. However, when I tried 100 and 250 for the window size but the matrix has the same shape. it would be great if you can provide some insights on this! Thanks!
<img width="640" alt="image" src="https://user-images.githubusercontent.com/16257776/227666253-ecb0cd0b-f76f-4583-a9c6-a137984734fc.png">

### Version information

-----
anndata             0.8.0
infercnvpy          0.4.1
matplotlib          3.6.2
numpy               1.21.6
pandas              1.5.0
phenograph          1.5.7
scanpy              1.9.1
scipy               1.9.1
seaborn             0.12.2
session_info        1.0.0
sklearn             1.1.2
statsmodels         0.13.2
tqdm                4.64.1
-----
PIL                 9.2.0
asciitree           NA
asttokens           NA
backcall            0.2.0
beta_ufunc          NA
binom_ufunc         NA
brotli              NA
cffi                1.15.1
click               8.1.3
cloudpickle         2.2.0
colorama            0.4.5
cupy                11.2.0
cupy_backends       NA
cupyx               NA
cycler              0.10.0
cython_runtime      NA
cytoolz             0.12.0
dask                2022.9.2
dateutil            2.8.2
debugpy             1.6.3
decorator           5.1.1
defusedxml          0.7.1
distributed         2022.9.2
entrypoints         0.4
executing           1.1.1
fasteners           0.17.3
fastrlock           0.8
fsspec              2022.8.2
google              NA
gtfparse            NA
h5py                3.7.0
heapdict            NA
hypergeom_ufunc     NA
igraph              0.10.1
importlib_metadata  NA
ipykernel           6.15.2
ipywidgets          8.0.2
jedi                0.18.1
jinja2              3.1.2
joblib              1.2.0
kiwisolver          1.4.4
leidenalg           0.9.0
llvmlite            0.39.1
locket              NA
lz4                 4.0.0
markupsafe          2.1.1
matplotlib_inline   0.1.6
mpl_toolkits        NA
msgpack             1.0.4
natsort             8.2.0
nbinom_ufunc        NA
ncf_ufunc           NA
numba               0.56.3
numcodecs           0.10.2
packaging           21.3
parso               0.8.3
pexpect             4.8.0
pickleshare         0.7.5
pkg_resources       NA
polars              0.16.14
prompt_toolkit      3.0.31
psutil              5.9.2
ptyprocess          0.7.0
pure_eval           0.2.2
pyarrow             9.0.0
pydev_ipython       NA
pydevconsole        NA
pydevd              2.8.0
pydevd_file_utils   NA
pydevd_plugins      NA
pydevd_tracing      NA
pygments            2.13.0
pynvml              11.4.1
pyparsing           3.0.9
pyreadr             0.4.7
pytz                2022.4
setuptools          60.10.0
six                 1.16.0
sortedcontainers    2.4.0
sphinxcontrib       NA
stack_data          0.5.1
tblib               1.7.0
texttable           1.6.4
threadpoolctl       3.1.0
tlz                 0.12.0
toolz               0.12.0
tornado             6.1
traitlets           5.4.0
typing_extensions   NA
urllib3             1.26.11
wcwidth             0.2.5
xarray              2022.10.0
yaml                6.0
zarr                2.13.3
zict                2.2.0
zipp                NA
zmq                 24.0.1
zoneinfo            NA
-----
IPython             8.4.0
jupyter_client      7.0.6
jupyter_core        4.11.1
-----
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) [GCC 10.3.0]
Linux-3.10.0-957.12.2.el7.x86_64-x86_64-with-glibc2.17
-----
Session information updated at 2023-03-24 20:16

**Comment by mmfalco** [comment]
@YubinXie I think you are confusing two different parameters. One thing is the `window_size`: size of the running window (number of genes in to include in the window); the other parameter is the `step` : only compute every nth running window where n = step. Set to 1 to compute all windows. If you change the first you change how many genes are used for each step, but you won't change the number of steps, that is why you get the same size matrix.

**Comment by YubinXie** [comment]
> @YubinXie I think you are confusing two different parameters. One thing is the `window_size`: size of the running window (number of genes in to include in the window); the other parameter is the `step` : only compute every nth running window where n = step. Set to 1 to compute all windows. If you change the first you change how many genes are used for each step, but you won't change the number of steps, that is why you get the same size matrix.

Oh I see. so as the default step as 10, each value in the output is the the average of 10 genes CNV score. Now it makes sense!
