### ISSUE TITLE
copycat memory issue 

### ISSUE THREAD

**Issue by YubinXie** [icbi-lab/infercnvpy#75]
### Report

I ran into memory issue when I ran the copycat. The gene and cell number are shown below. I was wondering if there is a general guide on the number of cells for this method. Many thanks!!

```
[1] "running copykat v1.1.0"
[1] "step1: read and filter data ..."
[1] "22318 genes, 73901 cells in raw data"
[1] "8197 genes past LOW.DR filtering"
[1] "step 2: annotations gene coordinates ..."
[1] "start annotation ..."
[1] "step 3: smoothing data with dlm ..."
WARNING:rpy2.rinterface_lib.callbacks:R[write to console]: Error in mcfork() : 
  unable to fork, possible reason: Cannot allocate memory
Calls: <Anonymous> ... <Anonymous> -> copykat -> <Anonymous> -> lapply -> FUN -> mcfork
```

**Comment by YubinXie** [comment]
I reduced the number of jobs and now it works.

**Comment by grst** [comment]
Hi @YubinXie, as infercnvpy is just a thin wrapper around the copycat function, it's best to ask this question in the copykat repo! 

Cheers, 
Gregor
