### ISSUE TITLE
Are we able to use output of infercnvpy for drawing phylogenetic trees?

### ISSUE THREAD

**Issue by tingxie2020** [icbi-lab/infercnvpy#88]
### Description of feature

Such as drawing phylogenetic tree by uphyloplot2? 
Thank you!

**Comment by grst** [comment]
Hi, the uphyloplot2 package looks interesting. In principle, it should be possible to calculate a dendrogram using infercnvpy and run it through uphyloplot2 for plotting. 

I currently don't have the time to pursue this though, but if you try it out, let me know how it goes and consider sending a pull request!

**Comment by yitengfei120011** [comment]
hi,I want that too.
Can you tell me how to use infercnvpy output to draw the phylogenetic tree using uphyloplot2,
I see that the R version of infercnv has output results that can be directly used in uphyloplot2, but I do not know how to use infercnvpy results
